name:                denotational
version:             0.1.0.0
synopsis:            Denotational Semantics
license:             BSD3
author:              Type Systems Course
maintainer:          example@example.com
category:            Education
build-type:          Simple

dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - megaparsec
  - parser-combinators
  - text

library:
  source-dirs: src
  exposed-modules:
    - Syntax
    - Domain
    - Denotation
    - Parser
    - Pretty

executables:
  denotational-repl:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - denotational

tests:
  denotational-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - denotational
      - hspec
