name: dependent-types-eliminators
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- megaparsec >= 9.0
- parser-combinators
- text

ghc-options:
- -Wall

library:
  source-dirs:
  - src
  - exercises

executables:
  dependent-types-eliminators-repl:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dependent-types-eliminators

tests:
  dependent-types-eliminators-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - dependent-types-eliminators
    - hspec
